version: '3.4'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - /docker/mysql/data:/var/lib/mysql
    env_file:
      - ./app/.env
    ports:
      - 3306:3006
